In [1]:
"""Stop Words"""

'Stop Words'

In [3]:
import spacy
from spacy.lang.en.stop_words import STOP_WORDS


nlp = spacy.load("en_core_web_sm")

print(f"Length of Stop Words: {len(STOP_WORDS)}")

for stop_word in STOP_WORDS:
    print(stop_word)

Length of Stop Words: 326
together
various
she
against
toward
due
's
’m
few
n’t
became
have
they
might
mostly
does
across
hereafter
seem
under
hers
into
nowhere
something
were
whole
an
whereby
her
n‘t
a
being
also
our
make
of
anyway
beyond
nine
although
thence
since
often
yourself
amongst
not
only
mine
with
what
yet
such
get
then
once
very
put
we
whatever
must
name
who
else
do
ours
show
over
thereafter
further
along
after
meanwhile
while
towards
us
ten
say
sometimes
first
either
wherein
your
still
’s
third
afterwards
front
much
‘re
latterly
whereafter
indeed
hereby
’re
besides
fifteen
'm
any
hundred
anything
himself
six
however
seemed
around
neither
nobody
three
yours
alone
onto
all
their
’ve
regarding
somehow
him
otherwise
should
on
has
before
become
my
sometime
moreover
whence
formerly
did
becomes
without
fifty
you
thus
beside
is
last
that
until
becoming
me
had
are
whether
whereas
least
former
could
nevertheless
them
by
about
one
'd
among
others
anyone
whose
now
thru
anyhow
than
five
none
i
above
nor
side
anywhere
therein
move
quite
ourselves
hence
thereby
because
somewhere
whereupon
see
behind
but
‘m
everywhere
this
themselves
forty
would
throughout
using
which
upon
thereupon
never
cannot
for
even
already
‘ll
please
between
twelve
except
therefore
each
eleven
been
whither
full
enough
done
or
everyone
ca
unless
every
whenever
was
how
it
up
top
other
perhaps
n't
here
as
herself
and
latter
several
almost
doing
part
‘ve
wherever
its
someone
used
re
his
made
amount
elsewhere
keep
off
eight
‘s
will
no
seeming
take
twenty
four
at
really
hereupon
've
through
can
rather
to
too
just
'll
where
again
there
everything
may
whoever
both
per
am
same
always
herein
well
’d
serious
he
whom
itself
out
bottom
many
seems
some
below
via
two
give
these
beforehand
the
down
in
back
those
most
so
’ll
call
during
yourselves
're
why
noone
nothing
within
from
though
be
less
‘d
next
more
ever
namely
another
own
empty
sixty
when
go
if
myself

In [8]:
text = """The quick brown fox jumps over the lazy dog while the sun sets slowly behind the mountains in the distance. She was walking to the store when she realized that she had forgotten her wallet at home, so she had to turn around and go back for it. Although the weather was quite cold, a few of the children were still playing outside in the park, running and laughing as if they had not a care in the world. It is often said that the best way to learn something new is to practice it every single day, even if only for a short amount of time."""

doc = nlp(text)

stop_words = [token for token in doc if token.is_stop]

print(f"Length of Stop Words: {len(stop_words)}")

for token in doc:
    if token.is_stop:
        print(token.text)

Length of Stop Words: 69
The
over
the
while
the
behind
the
in
the
She
was
to
the
when
she
that
she
had
her
at
so
she
had
to
around
and
go
back
for
it
Although
the
was
quite
a
few
of
the
were
still
in
the
and
as
if
they
had
not
a
in
the
It
is
often
that
the
to
something
is
to
it
every
even
if
only
for
a
amount
of

In [9]:
doc_excluding_stop_wrods = [token for token in doc if not token.is_stop and not token.is_punct]
print(doc_excluding_stop_wrods)

[quick, brown, fox, jumps, lazy, dog, sun, sets, slowly, mountains, distance, walking, store, realized, forgotten, wallet, home, turn, weather, cold, children, playing, outside, park, running, laughing, care, world, said, best, way, learn, new, practice, single, day, short, time]

In [10]:
def preprocess(text):
    doc = nlp(text)
    return [token for token in doc if not token.is_stop and not token.is_punct]

In [11]:
import pandas as pd

df = pd.read_json("doj_press.json", lines=True)
df.head()

,id,title,contents,date,topics,components
0,None,Convicted Bomb Plotter Sentenced to 30 Years,"PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...",2014-10-01T00:00:00-04:00,[],[National Security Division (NSD)]
1,12-919,$1 Million in Restitution Payments Announced t...,WASHINGTON – North Carolina’s Waccamaw River...,2012-07-25T00:00:00-04:00,[],[Environment and Natural Resources Division]
2,11-1002,$1 Million Settlement Reached for Natural Reso...,BOSTON– A $1-million settlement has been...,2011-08-03T00:00:00-04:00,[],[Environment and Natural Resources Division]
3,10-015,10 Las Vegas Men Indicted \r\nfor Falsifying V...,WASHINGTON—A federal grand jury in Las Vegas...,2010-01-08T00:00:00-05:00,[],[Environment and Natural Resources Division]
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]

In [12]:
print(df.shape)

(13087, 6)

In [13]:
# Filter the dataframe where topics is a empty list
df = df[df["topics"].str.len() != 0]
df.head()

,id,title,contents,date,topics,components
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division]
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U..."
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division]
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]"

In [14]:
print(df.shape)

(4688, 6)

In [16]:
# Create a new column excluding stop words
df["contents_excluding_stop_words"] = df["contents"].apply(preprocess)
df.head()

,id,title,contents,date,topics,components,contents_excluding_stop_words
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division],"[U.S., Department, Justice, U.S., Environmenta..."
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division],"[131, count, criminal, indictment, unsealed, t..."
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U...","[United, States, Attorney, Office, Middle, Dis..."
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division],"[21st, Century, Oncology, LLC, agreed, pay, $,..."
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]","[21st, Century, Oncology, Inc., certain, subsi..."

In [18]:
# Exercise
# From a given text return the count of stop words
text = """Every morning, before the sun had fully risen over the hills, an old fisherman would walk down to the edge of the lake where his small wooden boat was tied. He had been doing this for as long as anyone in the village could remember, and although he was no longer as strong as he used to be, he refused to give up the routine that had defined most of his life. Some of the younger fishermen often asked him why he did not simply retire and let others take over, but he would only smile and say that the lake was the one place where he felt truly at peace.
One day, while he was preparing his nets, a young boy from the village approached him and asked if he could come along. The old man hesitated at first, because he was not used to having company on his trips, but there was something about the boy's curiosity that reminded him of himself many years ago. So he agreed, and together they pushed the boat out into the calm, glassy water.
As they drifted further from the shore, the boy asked a lot of questions — about the fish, about the weather, and about why the old man had never left the village even though he could have gone anywhere he wanted. The fisherman explained that it was not because he lacked the opportunity, but because he had never found anything that felt more important than this lake, this boat, and these quiet mornings. The boy did not fully understand what he meant, but he nodded anyway, because there was something comforting in the way the old man spoke.
By the time they returned to the shore, the sun was high in the sky, and the village had begun to wake up. The old man handed the boy a small fish and told him that if he wanted to learn how to fish properly, he should come back tomorrow, and the day after that, and every day until he no longer needed to ask why. The boy smiled and promised that he would.
"""

doc = nlp(text)

stop_words = [token for token in doc if token.is_stop]

print(f"Length of Stop Words: {len(stop_words)}")

# Find the percentage of stop words compared to total words in the text
total_words_count = len(doc)
total_stop_words_count = len(stop_words)

percentage_stop_words = (total_stop_words_count / total_words_count) * 100
print(f"Percentage of Stop words presented in the given text: {percentage_stop_words} %")

Length of Stop Words: 228
Percentage of Stop words presented in the given text: 57.72151898734177 %

In [20]:
# Remove 'not' from the predefined stop words in spacy
print(nlp.vocab["not"].is_stop)
nlp.vocab["not"].is_stop = False
print(nlp.vocab["not"].is_stop)

True
False

In [ ]:
# From a given text, print the frequency and most frequently used words
text = """Every morning, before the sun had fully risen over the hills, an old fisherman would walk down to the edge of the lake where his small wooden boat was tied. He had been doing this for as long as anyone in the village could remember, and although he was no longer as strong as he used to be, he refused to give up the routine that had defined most of his life. Some of the younger fishermen often asked him why he did not simply retire and let others take over, but he would only smile and say that the lake was the one place where he felt truly at peace.
One day, while he was preparing his nets, a young boy from the village approached him and asked if he could come along. The old man hesitated at first, because he was not used to having company on his trips, but there was something about the boy's curiosity that reminded him of himself many years ago. So he agreed, and together they pushed the boat out into the calm, glassy water.
As they drifted further from the shore, the boy asked a lot of questions — about the fish, about the weather, and about why the old man had never left the village even though he could have gone anywhere he wanted. The fisherman explained that it was not because he lacked the opportunity, but because he had never found anything that felt more important than this lake, this boat, and these quiet mornings. The boy did not fully understand what he meant, but he nodded anyway, because there was something comforting in the way the old man spoke.
By the time they returned to the shore, the sun was high in the sky, and the village had begun to wake up. The old man handed the boy a small fish and told him that if he wanted to learn how to fish properly, he should come back tomorrow, and the day after that, and every day until he no longer needed to ask why. The boy smiled and promised that he would.
"""

doc = nlp(text)

remaining_tokens = []

for token in doc:
    if not token.is_stop or not token.is_punct:
        remaining_tokens.append(token.text)

token_frequency = {}
for token in remaining_tokens:
    if token != "\n" and token != " ":
        if token not in token_frequency:
            token_frequency[token] = 1
        else:
            token_frequency[token] += 1

max_frequent_token = max(token_frequency.keys(), key=(lambda key: token_frequency[key]))

print(f"Maximum frequency word: {max_frequent_token}")

Maximum frequency word: India